#!/bin/sh

if [ "$2" = "--light-theme" ]; then
    theme_0='#ffffff'
    theme_1='#000000'
else
    theme_0='#000000'
    theme_1='#ffffff'
fi

case $1 in

  --all)

    app_list=$(cat "$HOME"/.local/share/applications/*.desktop |\
      grep '^Name=.*\|^Exec=.*' | grep -vw 'Qube Settings\|qubes-vm-settings')


    chosen=$(echo "$app_list" | grep '^Name=.*' | cut -c 6- |\
      dmenu -f -nb $theme_0 -nf $theme_1 -sb $theme_1 -sf $theme_0)

    if [ -n "$chosen" ]; then

      if ! $(echo "$app_list" | grep -A1 "$chosen" |\
        sed 1d | cut -c 6-); then exit 2; fi

      exit 0
    fi

    exit 1;;

  --focused)

    qube=$(xprop -id "$(xdotool getwindowfocus)" _QUBES_VMNAME | cut -f2 -d\")

    if [ -n "$qube" ]; then

      qube_label=$(qvm-ls --raw-data "$qube" -O LABEL)

      # Change label colors according to 
      # ~/.config/qmenu.conf if that file exists.
      if [ -f "$HOME/.config/qmenu.conf" ]; then

        qube_label=$(grep "^$qube_label=" "$HOME"/.config/qmenu.conf |\
          cut -d= -f2)
      fi

      app_list=$(cat "$HOME"/.local/share/qubes-appmenus/"$qube"/apps/*.desktop |\
        grep '^Name=.*\|^Exec=.*' |\
        grep -vw 'Qube Settings\|qubes-vm-settings')

      chosen=$(echo "$app_list" | grep '^Name=.*' | cut -f2- -d: |\
        dmenu -p "$qube:" -f -nb $theme_0 -nf $theme_1 -sb "$qube_label" -sf $theme_1)

      if [ -n "$chosen" ]; then

        if ! $(echo "$app_list" | grep -A1 "$chosen" |\
          sed 1d | cut -c 6-); then exit 2; fi

        exit 0
      fi

      exit 1
    fi

    exit 2;;

  *)

    printf "$0 [OPTION] (--light-theme)\nLaunch domU applications.\n\n --all\n --focused\n\n\nqmenu v1.2.6\n<https://github.com/sine3o14nnae/qmenu/>\n<https://gitlab.com/sine3o14nnae/qmenu/>\n\n"

    if [ "$1" = "--help" ]; then exit 0; else exit 2; fi
esac
