#!/bin/sh

dmenu() {

command dmenu -f -nb "$theme_0" -nf "$theme_1" -sb "$theme_1" -sf "$theme_0" "$@"
}

get_qube_label() {

# Change label colors according to user input.
qube_label=$(echo "$@" | tr ' ' '\n' |\
	grep "\--$(qvm-prefs "$qube" label)" | cut -d= -f2)

if [ -z "$qube_label" ]; then qube_label=$theme_1; fi
}


if [ "$2" = "--light-theme" ]; then

	theme_0='#ffffff'
	theme_1='#000000'
else

	theme_0='#000000'
	theme_1='#ffffff'
fi

case $1 in

	--all)

		devices_list=$(qvm-block ls | sed -e 's/^/|block| /' & qvm-device mic ls |\
			sed -e 's/^/|mic| /' & qvm-usb ls | sed -e 's/^/|usb| /');;

	--block|--mic|--usb)

		device_type=$(echo "$1" | cut -c 3-)

		devices_list=$(qvm-device "$device_type" | sed -e "s/^/|$device_type| /");;

	*)

		printf "Usage: $0 [OPTION] (--light-theme) (--{LABEL}=#{HEX TRIPLET})...\nList and manage your connected devices via dmenu.\n\n --all\n --block\n --mic\n --usb\n\n"

		if [ "$1" = "--help" ]; then exit 0; fi; exit 2
esac

qube_list=$(qvm-ls --no-spinner --running -O name,label |\
	grep -v '^dom0 \|^sys-usb' |\
	sed '1d; s/ red/ 1\@ /g; s/ orange/ 2\@ /g; s/ yellow/ 3\@ /g; s/ green/ 4\@ /g; s/ gray/ 5\@ /g; s/ blue/ 6\@ /g; s/ purple/ 7\@ /g; s/ black/ 8\@ /g' |\
	sort -k2,2 |\
	sed 's/ 1\@ / red/g; s/ 2\@ / orange/g; s/ 3\@ / yellow/g; s/ 4\@ / green/g; s/ 5\@ / gray/g; s/ 6\@ / blue/g; s/ 7\@ / purple/g; s/ 8\@ / black/g')

device=0

while [ -n "$device" ]; do

	device=$(echo "$devices_list" | sort -r -k1,2 | dmenu -l 32)

	if [ "$1" = "--all" ]; then

		device_type=$(echo "$device" | cut -d\| -f2)
	fi

	if [ -n "$device" ] && [ "$(echo "$device" | wc -l)" -eq 1 ]; then

		device_id=$(echo "$device" | cut -f2 -d\ )

		if [ "$device_type" = "block" ]; then

			device_name=$(echo "$device" | awk '{print $3,$4}')
			qube=$(echo "$device" | awk '{print $5}')
		else

			device_name=$(echo "$device" | awk '{print $3}')
			qube=$(echo "$device" | awk '{print $4}')
		fi

		if [ -z "$qube" ]; then

			qube=$(echo "$qube_list" | dmenu -p "attach to:" -l 32 | cut -f1 -d\ )

			if [ -n "$qube" ]; then

				get_qube_label "$@"

				prompt=$(printf "No\nYes" | dmenu -sb "$qube_label" -i\
					-p "Attach '$device_name' to $qube?")

				if [ "$prompt" = "Yes" ]; then

					qvm-device "$device_type" attach -q "$qube" "$device_id" && exit 0

					echo "Quit..." |\
						dmenu -p "Error: Could not attach device!" > /dev/null 2>&1

					exit 2
				fi
			fi
		else

			get_qube_label "$@"

			prompt=$(printf "No\nYes" | dmenu -sb "$qube_label" -i\
				-p "Detach '$device_name' from $qube?")

			if [ "$prompt" = "Yes" ]; then

				qvm-device "$device_type" detach -q "$qube" "$device_id" && exit 0

				echo "Quit..." |\
					dmenu -p "Error: Could not detach device!" > /dev/null 2>&1

				exit 2
			fi
		fi
	fi
done

exit 1
